names=["7_SEG", "Basic", "DOS", "MacPaint", "Mario", "Pokemon", "StarryHorizon", "Tetris"]

[path]
library_dirpath = "lib/Watchy"
watchface_dirpath = "lib/Watchy/examples/WatchFaces"
settings_template_filepath = "templates/settings.h.template"
uses_folder_hierarchy = true
