names=["PipBoy"]

[path]
library_dirpath = "lib/watchy-pipboy"
watchface_dirpath = "lib/watchy-pipboy/pipboy"
settings_template_filepath = "templates/settings.h.template"
uses_folder_hierarchy = false
