names=["Starfield"]

[path]
library_dirpath = "lib/watchy-starfield"
watchface_dirpath = "lib/watchy-starfield"
settings_template_filepath = "templates/settings.h.template"
uses_folder_hierarchy = false
